// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 96907516;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'grin_wallet_bridge',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<BigInt> crateApiGetNodeTip();

  Future<String> crateApiGetNodeUrl();

  Future<String> crateApiOwnerListenerStart();

  Future<String> crateApiOwnerListenerStatus();

  Future<void> crateApiSetNodeUrl({required String url});

  Future<String> crateApiTorStart({required String listenAddr});

  Future<String> crateApiTorStatus();

  Future<void> crateApiTorStop();

  Future<String> crateApiWalletActiveAccount();

  Future<void> crateApiWalletCancelTx({required int txId});

  Future<String> crateApiWalletCreate(
      {required String dataDir,
      required String passphrase,
      required BigInt mnemonicLength});

  Future<String> crateApiWalletCreateAccount({required String label});

  Future<String> crateApiWalletFinalizeSlatepack(
      {required String message, required bool postTx, required bool fluff});

  Future<String> crateApiWalletGetAddress();

  Future<BigInt> crateApiWalletGetBalance();

  Future<String> crateApiWalletInfo();

  Future<void> crateApiWalletInitOrOpen(
      {required String dataDir, required String passphrase});

  Future<String> crateApiWalletInspectSlatepack({required String message});

  Future<String> crateApiWalletIssueInvoice({required BigInt amountNano});

  Future<String> crateApiWalletListAccounts();

  Future<String> crateApiWalletListOutputs(
      {required bool includeSpent, required bool refreshFromNode});

  Future<String> crateApiWalletListTransactions(
      {required bool refreshFromNode});

  Future<String> crateApiWalletPaymentProof({required int txId});

  Future<String> crateApiWalletProcessInvoice({required String message});

  Future<String> crateApiWalletReceiveSlatepack({required String message});

  Future<void> crateApiWalletRepostTx({required int txId, required bool fluff});

  Future<void> crateApiWalletRestoreFromSeed(
      {required String dataDir,
      required String passphrase,
      required String phrase});

  Future<String> crateApiWalletScan(
      {required bool deleteUnconfirmed,
      BigInt? startHeight,
      BigInt? backwardsFromTip});

  Future<String> crateApiWalletSeedPhrase(
      {required String dataDir, required String passphrase});

  Future<String> crateApiWalletSendSlatepack(
      {required String to, required BigInt amountNano});

  Future<String> crateApiWalletSetActiveAccount({required String label});

  Future<void> crateApiWalletSync();

  Future<String> crateApiWalletTransactionSlatepack({required int txId});

  Future<String> crateApiWalletVerifyPaymentProof({required String payload});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<BigInt> crateApiGetNodeTip() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGetNodeTipConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetNodeTipConstMeta => const TaskConstMeta(
        debugName: "get_node_tip",
        argNames: [],
      );

  @override
  Future<String> crateApiGetNodeUrl() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGetNodeUrlConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetNodeUrlConstMeta => const TaskConstMeta(
        debugName: "get_node_url",
        argNames: [],
      );

  @override
  Future<String> crateApiOwnerListenerStart() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiOwnerListenerStartConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOwnerListenerStartConstMeta => const TaskConstMeta(
        debugName: "owner_listener_start",
        argNames: [],
      );

  @override
  Future<String> crateApiOwnerListenerStatus() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiOwnerListenerStatusConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOwnerListenerStatusConstMeta =>
      const TaskConstMeta(
        debugName: "owner_listener_status",
        argNames: [],
      );

  @override
  Future<void> crateApiSetNodeUrl({required String url}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSetNodeUrlConstMeta,
      argValues: [url],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSetNodeUrlConstMeta => const TaskConstMeta(
        debugName: "set_node_url",
        argNames: ["url"],
      );

  @override
  Future<String> crateApiTorStart({required String listenAddr}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(listenAddr, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiTorStartConstMeta,
      argValues: [listenAddr],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTorStartConstMeta => const TaskConstMeta(
        debugName: "tor_start",
        argNames: ["listenAddr"],
      );

  @override
  Future<String> crateApiTorStatus() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiTorStatusConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTorStatusConstMeta => const TaskConstMeta(
        debugName: "tor_status",
        argNames: [],
      );

  @override
  Future<void> crateApiTorStop() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiTorStopConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTorStopConstMeta => const TaskConstMeta(
        debugName: "tor_stop",
        argNames: [],
      );

  @override
  Future<String> crateApiWalletActiveAccount() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletActiveAccountConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletActiveAccountConstMeta =>
      const TaskConstMeta(
        debugName: "wallet_active_account",
        argNames: [],
      );

  @override
  Future<void> crateApiWalletCancelTx({required int txId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_32(txId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletCancelTxConstMeta,
      argValues: [txId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletCancelTxConstMeta => const TaskConstMeta(
        debugName: "wallet_cancel_tx",
        argNames: ["txId"],
      );

  @override
  Future<String> crateApiWalletCreate(
      {required String dataDir,
      required String passphrase,
      required BigInt mnemonicLength}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dataDir, serializer);
        sse_encode_String(passphrase, serializer);
        sse_encode_usize(mnemonicLength, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletCreateConstMeta,
      argValues: [dataDir, passphrase, mnemonicLength],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletCreateConstMeta => const TaskConstMeta(
        debugName: "wallet_create",
        argNames: ["dataDir", "passphrase", "mnemonicLength"],
      );

  @override
  Future<String> crateApiWalletCreateAccount({required String label}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(label, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletCreateAccountConstMeta,
      argValues: [label],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletCreateAccountConstMeta =>
      const TaskConstMeta(
        debugName: "wallet_create_account",
        argNames: ["label"],
      );

  @override
  Future<String> crateApiWalletFinalizeSlatepack(
      {required String message, required bool postTx, required bool fluff}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(message, serializer);
        sse_encode_bool(postTx, serializer);
        sse_encode_bool(fluff, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletFinalizeSlatepackConstMeta,
      argValues: [message, postTx, fluff],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletFinalizeSlatepackConstMeta =>
      const TaskConstMeta(
        debugName: "wallet_finalize_slatepack",
        argNames: ["message", "postTx", "fluff"],
      );

  @override
  Future<String> crateApiWalletGetAddress() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletGetAddressConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletGetAddressConstMeta => const TaskConstMeta(
        debugName: "wallet_get_address",
        argNames: [],
      );

  @override
  Future<BigInt> crateApiWalletGetBalance() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletGetBalanceConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletGetBalanceConstMeta => const TaskConstMeta(
        debugName: "wallet_get_balance",
        argNames: [],
      );

  @override
  Future<String> crateApiWalletInfo() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletInfoConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletInfoConstMeta => const TaskConstMeta(
        debugName: "wallet_info",
        argNames: [],
      );

  @override
  Future<void> crateApiWalletInitOrOpen(
      {required String dataDir, required String passphrase}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dataDir, serializer);
        sse_encode_String(passphrase, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletInitOrOpenConstMeta,
      argValues: [dataDir, passphrase],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletInitOrOpenConstMeta => const TaskConstMeta(
        debugName: "wallet_init_or_open",
        argNames: ["dataDir", "passphrase"],
      );

  @override
  Future<String> crateApiWalletInspectSlatepack({required String message}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(message, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletInspectSlatepackConstMeta,
      argValues: [message],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletInspectSlatepackConstMeta =>
      const TaskConstMeta(
        debugName: "wallet_inspect_slatepack",
        argNames: ["message"],
      );

  @override
  Future<String> crateApiWalletIssueInvoice({required BigInt amountNano}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_64(amountNano, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletIssueInvoiceConstMeta,
      argValues: [amountNano],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletIssueInvoiceConstMeta => const TaskConstMeta(
        debugName: "wallet_issue_invoice",
        argNames: ["amountNano"],
      );

  @override
  Future<String> crateApiWalletListAccounts() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletListAccountsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletListAccountsConstMeta => const TaskConstMeta(
        debugName: "wallet_list_accounts",
        argNames: [],
      );

  @override
  Future<String> crateApiWalletListOutputs(
      {required bool includeSpent, required bool refreshFromNode}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_bool(includeSpent, serializer);
        sse_encode_bool(refreshFromNode, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletListOutputsConstMeta,
      argValues: [includeSpent, refreshFromNode],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletListOutputsConstMeta => const TaskConstMeta(
        debugName: "wallet_list_outputs",
        argNames: ["includeSpent", "refreshFromNode"],
      );

  @override
  Future<String> crateApiWalletListTransactions(
      {required bool refreshFromNode}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_bool(refreshFromNode, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletListTransactionsConstMeta,
      argValues: [refreshFromNode],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletListTransactionsConstMeta =>
      const TaskConstMeta(
        debugName: "wallet_list_transactions",
        argNames: ["refreshFromNode"],
      );

  @override
  Future<String> crateApiWalletPaymentProof({required int txId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_32(txId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletPaymentProofConstMeta,
      argValues: [txId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletPaymentProofConstMeta => const TaskConstMeta(
        debugName: "wallet_payment_proof",
        argNames: ["txId"],
      );

  @override
  Future<String> crateApiWalletProcessInvoice({required String message}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(message, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletProcessInvoiceConstMeta,
      argValues: [message],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletProcessInvoiceConstMeta =>
      const TaskConstMeta(
        debugName: "wallet_process_invoice",
        argNames: ["message"],
      );

  @override
  Future<String> crateApiWalletReceiveSlatepack({required String message}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(message, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletReceiveSlatepackConstMeta,
      argValues: [message],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletReceiveSlatepackConstMeta =>
      const TaskConstMeta(
        debugName: "wallet_receive_slatepack",
        argNames: ["message"],
      );

  @override
  Future<void> crateApiWalletRepostTx(
      {required int txId, required bool fluff}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_32(txId, serializer);
        sse_encode_bool(fluff, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletRepostTxConstMeta,
      argValues: [txId, fluff],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletRepostTxConstMeta => const TaskConstMeta(
        debugName: "wallet_repost_tx",
        argNames: ["txId", "fluff"],
      );

  @override
  Future<void> crateApiWalletRestoreFromSeed(
      {required String dataDir,
      required String passphrase,
      required String phrase}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dataDir, serializer);
        sse_encode_String(passphrase, serializer);
        sse_encode_String(phrase, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletRestoreFromSeedConstMeta,
      argValues: [dataDir, passphrase, phrase],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletRestoreFromSeedConstMeta =>
      const TaskConstMeta(
        debugName: "wallet_restore_from_seed",
        argNames: ["dataDir", "passphrase", "phrase"],
      );

  @override
  Future<String> crateApiWalletScan(
      {required bool deleteUnconfirmed,
      BigInt? startHeight,
      BigInt? backwardsFromTip}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_bool(deleteUnconfirmed, serializer);
        sse_encode_opt_box_autoadd_u_64(startHeight, serializer);
        sse_encode_opt_box_autoadd_u_64(backwardsFromTip, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 28, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletScanConstMeta,
      argValues: [deleteUnconfirmed, startHeight, backwardsFromTip],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletScanConstMeta => const TaskConstMeta(
        debugName: "wallet_scan",
        argNames: ["deleteUnconfirmed", "startHeight", "backwardsFromTip"],
      );

  @override
  Future<String> crateApiWalletSeedPhrase(
      {required String dataDir, required String passphrase}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dataDir, serializer);
        sse_encode_String(passphrase, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletSeedPhraseConstMeta,
      argValues: [dataDir, passphrase],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletSeedPhraseConstMeta => const TaskConstMeta(
        debugName: "wallet_seed_phrase",
        argNames: ["dataDir", "passphrase"],
      );

  @override
  Future<String> crateApiWalletSendSlatepack(
      {required String to, required BigInt amountNano}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(to, serializer);
        sse_encode_u_64(amountNano, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 30, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletSendSlatepackConstMeta,
      argValues: [to, amountNano],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletSendSlatepackConstMeta =>
      const TaskConstMeta(
        debugName: "wallet_send_slatepack",
        argNames: ["to", "amountNano"],
      );

  @override
  Future<String> crateApiWalletSetActiveAccount({required String label}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(label, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 31, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletSetActiveAccountConstMeta,
      argValues: [label],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletSetActiveAccountConstMeta =>
      const TaskConstMeta(
        debugName: "wallet_set_active_account",
        argNames: ["label"],
      );

  @override
  Future<void> crateApiWalletSync() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 32, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletSyncConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletSyncConstMeta => const TaskConstMeta(
        debugName: "wallet_sync",
        argNames: [],
      );

  @override
  Future<String> crateApiWalletTransactionSlatepack({required int txId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_32(txId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 33, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletTransactionSlatepackConstMeta,
      argValues: [txId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletTransactionSlatepackConstMeta =>
      const TaskConstMeta(
        debugName: "wallet_transaction_slatepack",
        argNames: ["txId"],
      );

  @override
  Future<String> crateApiWalletVerifyPaymentProof({required String payload}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(payload, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 34, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletVerifyPaymentProofConstMeta,
      argValues: [payload],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletVerifyPaymentProofConstMeta =>
      const TaskConstMeta(
        debugName: "wallet_verify_payment_proof",
        argNames: ["payload"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
